name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov coverage-badge
          # Install additional dependencies needed for testing
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          
      - name: Generate badges
        run: |
          python scripts/generate_badges.py
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          
      - name: Commit and push changes
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/assets/img/coverage.svg docs/assets/img/tests.svg README.md
          git commit -m "Update test and coverage badges" || echo "No changes to commit"
          git push 